FROM alpine:3.24.2

RUN apk add --no-cache build-base cmake ninja linux-headers perl pkgconf curl wget binutils patch

COPY build_deps.sh build.uv.sh build.hwloc.sh build.openssl.sh hwloc-visibility-notice.patch /opt/dependency-scripts/
RUN cd /opt/dependency-scripts && JOBS="$(nproc)" ./build_deps.sh
